import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import { Navbar } from "./components/Navbar";
import BootstrapClient from "./components/BootstrapClient";
import { ReactQueryClientProvider } from "./components/ReactQuerryClient";
import { CarrinhoProvider } from './context/carrinhoContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Loja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <ReactQueryClientProvider>
          <CarrinhoProvider>
            <Navbar />
            {children}
            <BootstrapClient />
          </CarrinhoProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
